import { GoogleGenAI } from '@google/genai';
export const MODEL = process.env.GEMINI_MODEL || 'gemini-3.6-flash';
export function json(res, status, payload) { res.status(status).setHeader('Content-Type','application/json; charset=utf-8').end(JSON.stringify(payload)); }
export function bodyOf(req) { if (req.body && typeof req.body === 'object') return req.body; if (typeof req.body === 'string') { try { return JSON.parse(req.body); } catch {} } return {}; }
export function getAI() { if (!process.env.GEMINI_API_KEY) { const err = new Error('GEMINI_API_KEY is missing. Add it in Vercel Environment Variables or your local .env file.'); err.code='MISSING_API_KEY'; throw err; } return new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY}); }
export function systemPrompt() { return `You are Scholar AI, the study assistant inside ScholarOS for a Vietnamese high-school student.\n\nGoals:\n- Help plan study sessions realistically.\n- Prefer Pomodoro 50 minutes focus + 10 minutes break.\n- Respect existing fixed classes and the student's rest/recovery.\n- Prioritize urgent/high-priority tasks and upcoming deadlines.\n- Suggest small repeatable habits rather than extreme routines.\n- Explain school subjects clearly when asked.\n- When proposing schedule changes, present them as suggestions and never claim that you changed the user's data.\n- Be concise, practical, and answer in Vietnamese unless the user asks otherwise.\n- Never request or expose API keys, passwords, or other secrets.`; }
export async function generate(input, config={}) { const ai=getAI(); return ai.models.generateContent({model:MODEL,contents:input,config:{maxOutputTokens:2200,...config}}); }
export function cleanJson(text) { const raw=String(text||'').trim().replace(/^```json\s*/i,'').replace(/^```\s*/i,'').replace(/```$/i,'').trim(); const a=raw.indexOf('{'), b=raw.lastIndexOf('}'); if(a>=0&&b>a) return JSON.parse(raw.slice(a,b+1)); throw new Error('AI did not return valid JSON.'); }
export function aiErrorMessage(err) { const status=Number.isInteger(err?.status)?err.status:500; if(err?.code==='MISSING_API_KEY') return {status:500,message:err.message}; if(status===401||status===403) return {status,message:'Gemini API key không hợp lệ hoặc không có quyền truy cập.'}; if(status===429) return {status,message:'Gemini API đang giới hạn tốc độ. Hãy thử lại sau.'}; if(status>=500) return {status:502,message:'Gemini API đang gặp lỗi tạm thời. Hãy thử lại sau.'}; return {status:status>=400&&status<600?status:500,message:err?.message||'AI request failed.'}; }
